//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int AuthorID { get; set; }
        public string AuthorName { get; set; }
        public string AuthorDivision { get; set; }
        public string AuthorArea { get; set; }
        public string AuthorAddress { get; set; }
        public string AuthorPhoneNumber { get; set; }
        public string AuthorEmail { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string AuthorBIO { get; set; }
        public string AuthorFacebookPageUrl { get; set; }
        public string AuthorPageUrl { get; set; }
        public string AuthorImage { get; set; }
        public int UserID { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
