//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogDetails { get; set; }
        public string BlogImage { get; set; }
        public Nullable<int> BloggerID { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
    
        public virtual Blogger Blogger { get; set; }
    }
}
