//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public string BookDetails { get; set; }
        public string BookImage { get; set; }
        public string BookPrice { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
