//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int JournalID { get; set; }
        public string JournalTitle { get; set; }
        public string JournalDetails { get; set; }
        public string JournalImage { get; set; }
        public int JournalPrice { get; set; }
        public int SubcategoryID { get; set; }
        public int PublisherDetails { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
