//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blogger()
        {
            this.Blogs = new HashSet<Blog>();
        }
    
        public int BloggerID { get; set; }
        public string BloggerName { get; set; }
        public string BloggerAddress { get; set; }
        public string BloggerDivision { get; set; }
        public string BloggerArea { get; set; }
        public string BloggerPhoneNumber { get; set; }
        public string BloggerEmail { get; set; }
        public string BloggerImage { get; set; }
        public string BloggerBio { get; set; }
        public string BloggerPageUrl { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blogs { get; set; }
        public virtual User User { get; set; }
    }
}
