//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookOrderAssign
    {
        public int BookorderID { get; set; }
        public int OrderID { get; set; }
        public int DeliveryManID { get; set; }
    
        public virtual BuyBook BuyBook { get; set; }
        public virtual DeliveryMan DeliveryMan { get; set; }
    }
}
