//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyJournal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyJournal()
        {
            this.AssignmentJournals = new HashSet<AssignmentJournal>();
            this.BuyJournalLists = new HashSet<BuyJournalList>();
        }
    
        public int JournalOrderID { get; set; }
        public int CustomerID { get; set; }
        public decimal TotalCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentJournal> AssignmentJournals { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyJournalList> BuyJournalLists { get; set; }
    }
}
