//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryMan()
        {
            this.AssignmentJournals = new HashSet<AssignmentJournal>();
            this.BookOrderAssigns = new HashSet<BookOrderAssign>();
        }
    
        public int DeliveryManID { get; set; }
        public string DeliveryManName { get; set; }
        public string DeliveryManAddress { get; set; }
        public string DeliveryManImage { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentJournal> AssignmentJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookOrderAssign> BookOrderAssigns { get; set; }
        public virtual User User { get; set; }
    }
}
