//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.BuyJournalLists = new HashSet<BuyJournalList>();
        }
    
        public int JournalID { get; set; }
        public string JournalTitle { get; set; }
        public string JournalDetails { get; set; }
        public string JournalImage { get; set; }
        public int JournalPrice { get; set; }
        public int SubcategoryID { get; set; }
        public int PublisherDetails { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyJournalList> BuyJournalLists { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
