//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_BookStore.Utility.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities5 : DbContext
    {
        public Entities5()
            : base("name=Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssignmentJournal> AssignmentJournals { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Blogger> Bloggers { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookOrderAssign> BookOrderAssigns { get; set; }
        public virtual DbSet<Borrow> Borrows { get; set; }
        public virtual DbSet<BuyBook> BuyBooks { get; set; }
        public virtual DbSet<BuyJournal> BuyJournals { get; set; }
        public virtual DbSet<BuyJournalList> BuyJournalLists { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryMan> DeliveryMen { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<OrderBookList> OrderBookLists { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
